version: '3.8'

services:
  database_service:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=weeabookpassword123
      - POSTGRES_USER=admin
    image: postgres:15.0-alpine